---
name: Manage Stale Branches
description: |
  This action deletes branches that have not had a commit in the last `stale-duration` (hours, days or weeks).

inputs:
  github-token:
    description: |
      GitHub Token with repository write access.
    required: false
    default: ${{ github.token }}
  stale-duration:
    description: Time threshold for stale branches (e.g., "60d", "2w", "1440h"). Accept only a single unit.
    required: false
    default: "60d"
  suggested-duration:
    description: Time threshold for suggested branches (e.g., "30d", "1w", "720h"). Accept only a single unit.
    required: false
    default: "30d"
  concurrency:
    description: Number of branches to process concurrently.
    required: false
    default: 4
  dry-run:
    description: Run in dry-run mode (no actual deletion).
    required: false
    default: true
  archive-stale:
    description: Archive instead of deleting stale branches.
    required: false
    default: false
  exclude-patterns:
    description: |
      Branches to exclude from cleanup.
      It can be a comma-separated list or a multiline string (yaml list).
      It can use regex patterns.
    required: false
    default: ""

outputs:
  summary:
    description: Summary of deleted/suggested branches.
  merged-branches:
    description: |
      JSON array string listing the merged branches which have been deleted.
      Used in dry-run mode, you can pass it easily to a matrix job to handle yourself these branches.
  merged-branches-count:
    description: Deleted merged branches count.
  stale-branches:
    description: |
      JSON array string listing the stale branches.
      Used in dry-run mode, you can pass it easily to a matrix job to handle yourself these branches.
  stale-branches-count:
    description: Stale branches count.
  suggested-branches:
    description: |
      JSON array string listing the branches suggested for deletion.
      Used in dry-run mode, you can pass it easily to a matrix job to handle yourself these branches.
  suggested-branches-count:
    description: Suggested branches count.

runs:
  using: node20
  main: dist/index.js

branding:
  icon: archive
  color: green
