name: 'Manage Stale Branches'
description: 'Delete already merged/stale branches and make suggestions on the ones which could be considered for deletion.'
inputs:
  gh_token:
    description: 'Provide the GITHUB_TOKEN secret to be used for cloning and branch deletions. Needs read/write access on your repository, so passing the secrets.GITHUB_TOKEN is recommended as set by default with read/write by GitHub.'
    required: true
  stale_older_than:
    description: 'Number of days after which branches are deleted if not merged in any branch'
    required: false
    default: '60'
  suggestions_older_than:
    description: 'Number of days after which branches are suggested for deletion if not merged in any branch'
    required: false
    default: '30'
  dry_run:
    description: 'Run the action in dry-run mode to let you visualise the changes before going live'
    required: false
    default: 'true'
  archive_stale:
    description: Instead of deleting the branches declared stale, the action will archive them creating a tag "archive/[branch name]". You can later unarchive them running "git checkout -b [branch name] refs/tags/archive/[branch name].
    required: false
    default: 'false'
  excluded_branches:
    description: 'List the branches you want to exclude from the cleanup process'
    required: false
    default: ''
outputs:
  message:
    description: 'Summarize the outcome of the cleanup process in a nice message mentioning deleted branches and suggestions (merged branches deleted are not mentioned)'
runs:
  using: 'docker'
  image: 'docker/Dockerfile'
  env:
    GH_TOKEN: ${{ inputs.gh_token }}
    STALE_OLDER_THAN: ${{ inputs.stale_older_than }}
    SUGGESTIONS_OLDER_THAN: ${{ inputs.suggestions_older_than }}
    DRY_RUN: ${{ inputs.dry_run }}
    ARCHIVE_STALE: ${{ inputs.archive_stale }}
    EXCLUDED_BRANCHES: ${{ inputs.excluded_branches }}
