name: 'Stale Branches'
description: 'Delete or archive old branches from repository'
inputs:
  stale_older_than:
    description: 'Number of days after which branches are deleted if not merged in any branch'
    required: false
    default: 90
  suggestions_older_than:
    description: 'Number of days after which branches are suggested for deletion if not merged in any branch'
    required: false
    default: 45
  dry_run:
    description: 'Run the action in dry-run mode to let you visualise the changes before going live'
    required: false
    default: false
  excluded_branches:
    description: 'List the branches you want to exclude from the cleanup process'
    required: false
    default: ''
outputs:
  branches_to_review:
    description: 'List the branches picked up by the action and suspected to be stale according to the suggestions_older_than value'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STALE_OLDER_THAN: ${{ inputs.stale_older_than }}
    SUGGESTIONS_OLDER_THAN: ${{ inputs.suggestions_older_than }}
    DRY_RUN: ${{ inputs.dry_run }}
    EXCLUDED_BRANCHES: ${{ inputs.excluded_branches }}
